version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: submit-postgres-db-test
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.test.local
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: submit-postgres-db-test-vol